language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer self-update
    - composer global require "fxp/composer-asset-plugin":"*"
    - composer install --prefer-source --no-interaction
